<?php
namespace Synapse\CoreBundle\Repository;

use Synapse\CoreBundle\Entity\EbiQuestionOptions;

class EbiQuestionOptionsRepository extends SynapseRepository
{

    const REPOSITORY_KEY = 'SynapseCoreBundle:EbiQuestionOptions';

    /**
     * Override find() to use PHP Typing
     *
     * @param mixed $id
     * @param null $lockMode
     * @param null $lockVersion
     * @return null|EbiQuestionOptions
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion); // TODO: Change the autogenerated stub
    }

    /**
     * Override FindBy To Use PHP Typing
     *
     * @param array $criteria
     * @param array|null $orderBy
     * @param int|null $limit
     * @param int|null $offset
     *
     * @return EbiQuestionOptions[]
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }


    /**
     * Override FindOneBy To Use PHP Typing
     *
     * @param array $criteria
     * @param array|null $orderBy
     *
     * @return EbiQuestionOptions|null
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy);
    }
}