<?php
namespace Synapse\CoreBundle\Repository;

/**
 * InstitutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Synapse\CoreBundle\Entity\OrganizationLang;
use Synapse\CoreBundle\Exception\SynapseException;


class OrganizationlangRepository extends SynapseRepository
{
    const REPOSITORY_KEY = 'SynapseCoreBundle:OrganizationLang';

    /**
     * Finds a single entity by a set of criteria.
     *
     * @param array $criteria
     * @param SynapseException $exception
     * @param array|null $orderBy
     * @param \Exception $exception
     *
     * @return OrganizationLang|null
     */
    public function findOneBy(array $criteria, $exception = null, array $orderBy = null)
    {
        $organizationLangEntity = parent::findOneBy($criteria, $orderBy);
        return $this->doesObjectExist($organizationLangEntity, $exception);
    }


    public function createOrganizationLang(OrganizationLang $organizationlang)
    {
        $em = $this->getEntityManager();
        $em->persist($organizationlang);
        return $organizationlang;
    }

    public function remove(OrganizationLang $organizationlang)
    {
        $em = $this->getEntityManager();
        $em->remove($organizationlang);
    }
    public function getOrganizationDetailsLang($orgID)
    {
        $em = $this->getEntityManager();

        $organization = $em->getRepository("SynapseCoreBundle:OrganizationLang")->find($orgID);

        return $organization;
    }
}