<?php

namespace Synapse\CoreBundle\Repository;

/**
 * OrgCohortNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgCohortNameRepository extends SynapseRepository
{

    const REPOSITORY_KEY = 'SynapseCoreBundle:OrgCohortName';
}
