<?php
namespace Synapse\CoreBundle\Repository;

/**
 * PersonMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Synapse\CoreBundle\Entity\PersonMetadata;

class PersonMetadataRepository extends SynapseRepository
{

    const REPOSITORY_KEY = 'SynapseCoreBundle:PersonMetadata';

    public function create(PersonMetadata $personMetadata)
    {
        $em = $this->getEntityManager();
        $em->persist($personMetadata);
        return $personMetadata;
    }

    public function remove(PersonMetadata $personMetadata)
    {
        $em = $this->getEntityManager();
        $em->remove($personMetadata);
    }
}
