<?php

use Codeception\TestCase\Test;

class StudentListDAOTest extends Test
{
    use Codeception\Specify;


    private $classLevelEbiMetadataId = 56;

    /**
     * @var \Symfony\Component\DependencyInjection\Container
     */
    private $container;

    /**
     * @var \Synapse\SearchBundle\DAO\StudentListDAO
     */
    private $studentListDAO;


    public function _before()
    {
        $this->container = $this->getModule('Symfony2')->kernel->getContainer();
        $this->studentListDAO = $this->container->get('student_list_dao');
    }


    public function testGetAdditionalStudentData()
    {
        $this->specify("Verify the functionality of the method getAdditionalStudentData", function ($studentIds, $timeZoneString, $sortBy, $offset, $recordsPerPage, $academicDatetime, $expectedResult) {

            $result = $this->studentListDAO->getAdditionalStudentData($studentIds, $this->classLevelEbiMetadataId, $timeZoneString, $sortBy, $offset, $recordsPerPage, $academicDatetime);
            verify($result)->equals($expectedResult);

        }, ["examples" =>
            [
                // Example 1:  Base example with default (name) sorting and no offset or limit.
                [[4775354, 4775483, 4775641, 4776313, 4776777, 4776996, 4777077], 'US/Eastern', null, null, null,'2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4775483,
                            'student_first_name' => 'Cristiano',
                            'student_last_name' => 'Bauer',
                            'external_id' => 4775483,
                            'student_primary_email' => 'MapworksBetaUser04775483@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'green',
                            'student_risk_image_name' => 'risk-level-icon-g.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775354,
                            'student_first_name' => 'Aryan',
                            'student_last_name' => 'Dawson',
                            'external_id' => 4775354,
                            'student_primary_email' => 'MapworksBetaUser04775354@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'yellow',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-implied.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776996,
                            'student_first_name' => 'Brennan',
                            'student_last_name' => 'Duarte',
                            'external_id' => 4776996,
                            'student_primary_email' => 'MapworksBetaUser04776996@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776313,
                            'student_first_name' => 'Aliana',
                            'student_last_name' => 'Frazier',
                            'external_id' => 4776313,
                            'student_primary_email' => 'MapworksBetaUser04776313@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776777,
                            'student_first_name' => 'Everett',
                            'student_last_name' => 'Ho',
                            'external_id' => 4776777,
                            'student_primary_email' => 'MapworksBetaUser04776777@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 2a:  Using limit and offset for first page
                [[4775354, 4775483, 4775641, 4776313, 4776777, 4776996, 4777077], 'US/Eastern', null, 0, 5, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4775483,
                            'student_first_name' => 'Cristiano',
                            'student_last_name' => 'Bauer',
                            'external_id' => 4775483,
                            'student_primary_email' => 'MapworksBetaUser04775483@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'green',
                            'student_risk_image_name' => 'risk-level-icon-g.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775354,
                            'student_first_name' => 'Aryan',
                            'student_last_name' => 'Dawson',
                            'external_id' => 4775354,
                            'student_primary_email' => 'MapworksBetaUser04775354@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'yellow',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-implied.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776996,
                            'student_first_name' => 'Brennan',
                            'student_last_name' => 'Duarte',
                            'external_id' => 4776996,
                            'student_primary_email' => 'MapworksBetaUser04776996@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 2b:  Using limit and offset for second page
                [[4775354, 4775483, 4775641, 4776313, 4776777, 4776996, 4777077], 'US/Eastern', null, 5, 5, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4776313,
                            'student_first_name' => 'Aliana',
                            'student_last_name' => 'Frazier',
                            'external_id' => 4776313,
                            'student_primary_email' => 'MapworksBetaUser04776313@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776777,
                            'student_first_name' => 'Everett',
                            'student_last_name' => 'Ho',
                            'external_id' => 4776777,
                            'student_primary_email' => 'MapworksBetaUser04776777@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 3a:  Sorting by student name ascending
                [[4775641, 4776313, 4777077], 'US/Eastern', '+student_last_name', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776313,
                            'student_first_name' => 'Aliana',
                            'student_last_name' => 'Frazier',
                            'external_id' => 4776313,
                            'student_primary_email' => 'MapworksBetaUser04776313@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 3b:  Sorting by student name descending
                [[4775641, 4776313, 4777077], 'US/Eastern', '-student_last_name', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4776313,
                            'student_first_name' => 'Aliana',
                            'student_last_name' => 'Frazier',
                            'external_id' => 4776313,
                            'student_primary_email' => 'MapworksBetaUser04776313@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 4a:  Sorting by risk ascending
                [[397277, 767634, 4775354, 4775483, 4775641, 4777077], 'US/Eastern', '+student_risk_status', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4775483,
                            'student_first_name' => 'Cristiano',
                            'student_last_name' => 'Bauer',
                            'external_id' => 4775483,
                            'student_primary_email' => 'MapworksBetaUser04775483@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'green',
                            'student_risk_image_name' => 'risk-level-icon-g.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775354,
                            'student_first_name' => 'Aryan',
                            'student_last_name' => 'Dawson',
                            'external_id' => 4775354,
                            'student_primary_email' => 'MapworksBetaUser04775354@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'yellow',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-implied.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 767634,
                            'student_first_name' => 'Audrey',
                            'student_last_name' => 'Booth',
                            'external_id' => 767634,
                            'student_primary_email' => 'MapworksBetaUser00767634@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 4b:  Sorting by risk descending
                [[397277, 767634, 4775354, 4775483, 4775641, 4777077], 'US/Eastern', '-student_risk_status', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 767634,
                            'student_first_name' => 'Audrey',
                            'student_last_name' => 'Booth',
                            'external_id' => 767634,
                            'student_primary_email' => 'MapworksBetaUser00767634@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775354,
                            'student_first_name' => 'Aryan',
                            'student_last_name' => 'Dawson',
                            'external_id' => 4775354,
                            'student_primary_email' => 'MapworksBetaUser04775354@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'yellow',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-implied.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775483,
                            'student_first_name' => 'Cristiano',
                            'student_last_name' => 'Bauer',
                            'external_id' => 4775483,
                            'student_primary_email' => 'MapworksBetaUser04775483@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'green',
                            'student_risk_image_name' => 'risk-level-icon-g.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 5a:  Sorting by intent to leave ascending
                [[397502, 767634, 4775354, 4776313, 4776777, 4777077], 'US/Eastern', '+student_intent_to_leave', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776777,
                            'student_first_name' => 'Everett',
                            'student_last_name' => 'Ho',
                            'external_id' => 4776777,
                            'student_primary_email' => 'MapworksBetaUser04776777@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775354,
                            'student_first_name' => 'Aryan',
                            'student_last_name' => 'Dawson',
                            'external_id' => 4775354,
                            'student_primary_email' => 'MapworksBetaUser04775354@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'yellow',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-implied.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776313,
                            'student_first_name' => 'Aliana',
                            'student_last_name' => 'Frazier',
                            'external_id' => 4776313,
                            'student_primary_email' => 'MapworksBetaUser04776313@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 397502,
                            'student_first_name' => 'Lee',
                            'student_last_name' => 'Ballard',
                            'external_id' => 397502,
                            'student_primary_email' => 'MapworksBetaUser00397502@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'gray',
                            'student_intent_to_leave_image_name' => 'leave-intent-not-stated.png',
                            'student_classlevel' => 'Senior',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 767634,
                            'student_first_name' => 'Audrey',
                            'student_last_name' => 'Booth',
                            'external_id' => 767634,
                            'student_primary_email' => 'MapworksBetaUser00767634@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 5b:  Sorting by intent to leave descending
                [[397502, 767634, 4775354, 4776313, 4776777, 4777077], 'US/Eastern', '-student_intent_to_leave', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4776313,
                            'student_first_name' => 'Aliana',
                            'student_last_name' => 'Frazier',
                            'external_id' => 4776313,
                            'student_primary_email' => 'MapworksBetaUser04776313@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'red',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775354,
                            'student_first_name' => 'Aryan',
                            'student_last_name' => 'Dawson',
                            'external_id' => 4775354,
                            'student_primary_email' => 'MapworksBetaUser04775354@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'yellow',
                            'student_intent_to_leave_image_name' => 'leave-intent-leave-implied.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776777,
                            'student_first_name' => 'Everett',
                            'student_last_name' => 'Ho',
                            'external_id' => 4776777,
                            'student_primary_email' => 'MapworksBetaUser04776777@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 397502,
                            'student_first_name' => 'Lee',
                            'student_last_name' => 'Ballard',
                            'external_id' => 397502,
                            'student_primary_email' => 'MapworksBetaUser00397502@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'gray',
                            'student_intent_to_leave_image_name' => 'leave-intent-not-stated.png',
                            'student_classlevel' => 'Senior',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 767634,
                            'student_first_name' => 'Audrey',
                            'student_last_name' => 'Booth',
                            'external_id' => 767634,
                            'student_primary_email' => 'MapworksBetaUser00767634@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 6a:  Sorting by class level ascending
                [[397277, 397502, 623363, 767634, 4775641, 4777077], 'US/Eastern', '+student_classlevel', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 767634,
                            'student_first_name' => 'Audrey',
                            'student_last_name' => 'Booth',
                            'external_id' => 767634,
                            'student_primary_email' => 'MapworksBetaUser00767634@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 623363,
                            'student_first_name' => 'Jon',
                            'student_last_name' => 'Robbins',
                            'external_id' => 623363,
                            'student_primary_email' => 'MapworksBetaUser00623363@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Junior',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 397502,
                            'student_first_name' => 'Lee',
                            'student_last_name' => 'Ballard',
                            'external_id' => 397502,
                            'student_primary_email' => 'MapworksBetaUser00397502@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'gray',
                            'student_intent_to_leave_image_name' => 'leave-intent-not-stated.png',
                            'student_classlevel' => 'Senior',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 6b:  Sorting by class level descending
                [[397277, 397502, 623363, 767634, 4775641, 4777077], 'US/Eastern', '-student_classlevel', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 397502,
                            'student_first_name' => 'Lee',
                            'student_last_name' => 'Ballard',
                            'external_id' => 397502,
                            'student_primary_email' => 'MapworksBetaUser00397502@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'gray',
                            'student_intent_to_leave_image_name' => 'leave-intent-not-stated.png',
                            'student_classlevel' => 'Senior',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 623363,
                            'student_first_name' => 'Jon',
                            'student_last_name' => 'Robbins',
                            'external_id' => 623363,
                            'student_primary_email' => 'MapworksBetaUser00623363@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Junior',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 767634,
                            'student_first_name' => 'Audrey',
                            'student_last_name' => 'Booth',
                            'external_id' => 767634,
                            'student_primary_email' => 'MapworksBetaUser00767634@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777077,
                            'student_first_name' => 'Case',
                            'student_last_name' => 'Bennett',
                            'external_id' => 4777077,
                            'student_primary_email' => 'MapworksBetaUser04777077@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 7a:  Sorting by activities logged ascending
                [[397277, 4775641, 4776388, 4776952, 4777308], 'US/Eastern', '+student_logins', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => '4776952',
                            'student_first_name' => 'Cohen',
                            'student_last_name' => 'Odom',
                            'external_id' => '4776952',
                            'student_primary_email' => 'MapworksBetaUser04776952@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => '1',
                            'last_activity_date' => '2016/02/25',
                            'last_activity' => 'Referral'
                        ],
                        [
                            'student_id' => 4776388,
                            'student_first_name' => 'Naya',
                            'student_last_name' => 'Moss',
                            'external_id' => 4776388,
                            'student_primary_email' => 'MapworksBetaUser04776388@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 2,
                            'last_activity_date' => '2016/03/22',
                            'last_activity' => 'Contact'
                        ],
                        [
                            'student_id' => 4777308,
                            'student_first_name' => 'Xzavier',
                            'student_last_name' => 'Lowe',
                            'external_id' => 4777308,
                            'student_primary_email' => 'MapworksBetaUser04777308@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 5,
                            'last_activity_date' => '2016/02/18',
                            'last_activity' => 'Note'
                        ]
                    ]
                ],
                // Example 7b:  Sorting by activities logged descending
                [[397277, 4775641, 4776388, 4776952, 4777308], 'US/Eastern', '-student_logins', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4777308,
                            'student_first_name' => 'Xzavier',
                            'student_last_name' => 'Lowe',
                            'external_id' => 4777308,
                            'student_primary_email' => 'MapworksBetaUser04777308@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 5,
                            'last_activity_date' => '2016/02/18',
                            'last_activity' => 'Note'
                        ],
                        [
                            'student_id' => 4776388,
                            'student_first_name' => 'Naya',
                            'student_last_name' => 'Moss',
                            'external_id' => 4776388,
                            'student_primary_email' => 'MapworksBetaUser04776388@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 2,
                            'last_activity_date' => '2016/03/22',
                            'last_activity' => 'Contact'
                        ],
                        [
                            'student_id' => 4776952,
                            'student_first_name' => 'Cohen',
                            'student_last_name' => 'Odom',
                            'external_id' => 4776952,
                            'student_primary_email' => 'MapworksBetaUser04776952@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 1,
                            'last_activity_date' => '2016/02/25',
                            'last_activity' => 'Referral'
                        ],
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 8a:  Sorting by last activity date ascending
                [[397277, 4775641, 4776388, 4776952, 4777308], 'US/Eastern', '+last_activity', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777308,
                            'student_first_name' => 'Xzavier',
                            'student_last_name' => 'Lowe',
                            'external_id' => 4777308,
                            'student_primary_email' => 'MapworksBetaUser04777308@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 5,
                            'last_activity_date' => '2016/02/18',
                            'last_activity' => 'Note'
                        ],
                        [
                            'student_id' => 4776952,
                            'student_first_name' => 'Cohen',
                            'student_last_name' => 'Odom',
                            'external_id' => 4776952,
                            'student_primary_email' => 'MapworksBetaUser04776952@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 1,
                            'last_activity_date' => '2016/02/25',
                            'last_activity' => 'Referral'
                        ],
                        [
                            'student_id' => 4776388,
                            'student_first_name' => 'Naya',
                            'student_last_name' => 'Moss',
                            'external_id' => 4776388,
                            'student_primary_email' => 'MapworksBetaUser04776388@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 2,
                            'last_activity_date' => '2016/03/22',
                            'last_activity' => 'Contact'
                        ]
                    ]
                ],
                // Example 8b:  Sorting by last activity date descending
                [[397277, 4775641, 4776388, 4776952, 4777308], 'US/Eastern', '-last_activity', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4776388,
                            'student_first_name' => 'Naya',
                            'student_last_name' => 'Moss',
                            'external_id' => 4776388,
                            'student_primary_email' => 'MapworksBetaUser04776388@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 2,
                            'last_activity_date' => '2016/03/22',
                            'last_activity' => 'Contact'
                        ],
                        [
                            'student_id' => 4776952,
                            'student_first_name' => 'Cohen',
                            'student_last_name' => 'Odom',
                            'external_id' => 4776952,
                            'student_primary_email' => 'MapworksBetaUser04776952@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 1,
                            'last_activity_date' => '2016/02/25',
                            'last_activity' => 'Referral'
                        ],
                        [
                            'student_id' => 4777308,
                            'student_first_name' => 'Xzavier',
                            'student_last_name' => 'Lowe',
                            'external_id' => 4777308,
                            'student_primary_email' => 'MapworksBetaUser04777308@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 5,
                            'last_activity_date' => '2016/02/18',
                            'last_activity' => 'Note'
                        ],
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ]
                    ]
                ],
                // Example 9:  Demonstrating secondary sorting by student last name, first name, and primary email.
                // Since the email is based on the student id in the functional testing database,
                // it's impossible to show that the last level of sorting is by email rather than person_id or external_id,
                // but this test at least demonstrates that it's deterministic.
                [[397277, 4775641, 4776388, 4776952, 4777308], 'US/Central', 'student_intent_to_leave', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 4775641,
                            'student_first_name' => 'Eleanor',
                            'student_last_name' => 'Brennan',
                            'external_id' => 4775641,
                            'student_primary_email' => 'MapworksBetaUser04775641@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4776388,
                            'student_first_name' => 'Naya',
                            'student_last_name' => 'Moss',
                            'external_id' => 4776388,
                            'student_primary_email' => 'MapworksBetaUser04776388@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'yellow',
                            'student_risk_image_name' => 'risk-level-icon-y.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 2,
                            'last_activity_date' => '2016/03/22',
                            'last_activity' => 'Contact'
                        ],
                        [
                            'student_id' => 397277,
                            'student_first_name' => 'Odin',
                            'student_last_name' => 'Banks',
                            'external_id' => 397277,
                            'student_primary_email' => 'MapworksBetaUser00397277@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'gray',
                            'student_risk_image_name' => 'risk-level-icon-gray.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => null,
                            'student_logins' => 0,
                            'last_activity_date' => null,
                            'last_activity' => null
                        ],
                        [
                            'student_id' => 4777308,
                            'student_first_name' => 'Xzavier',
                            'student_last_name' => 'Lowe',
                            'external_id' => 4777308,
                            'student_primary_email' => 'MapworksBetaUser04777308@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 5,
                            'last_activity_date' => '2016/02/18',
                            'last_activity' => 'Note'
                        ],
                        [
                            'student_id' => 4776952,
                            'student_first_name' => 'Cohen',
                            'student_last_name' => 'Odom',
                            'external_id' => 4776952,
                            'student_primary_email' => 'MapworksBetaUser04776952@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red',
                            'student_risk_image_name' => 'risk-level-icon-r1.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => 'Sophomore',
                            'student_logins' => 1,
                            'last_activity_date' => '2016/02/25',
                            'last_activity' => 'Referral'
                        ],
                    ]

                ],
                // Example 10:  Demonstrating that sorting by last_activity_date only sorts by the date and not the date and time,
                // with secondary sorting by student last name, first name, and primary email.
                // This example also demonstrates that timezone is taken into account as the date of one of these activities is the next day in UTC.
                // The actual timestamps of these activities, in order, are '2015-11-03 20:18:22', '2015-11-04 02:30:31', '2015-11-03 16:27:03'.
                [[1022155, 4776384, 4776910], 'US/Eastern', '-last_activity_date', null, null, '2016-9-1 00:00:00',
                    [
                        [
                            'student_id' => 1022155,
                            'student_first_name' => 'Amelie',
                            'student_last_name' => 'Dixon',
                            'external_id' => 1022155,
                            'student_primary_email' => 'MapworksBetaUser01022155@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 5,
                            'last_activity_date' => '2015/11/03',
                            'last_activity' => 'Contact'
                        ],
                        [
                            'student_id' => 4776910,
                            'student_first_name' => 'Edgar',
                            'student_last_name' => 'Kaufman',
                            'external_id' => 4776910,
                            'student_primary_email' => 'MapworksBetaUser04776910@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'red2',
                            'student_risk_image_name' => 'risk-level-icon-r2.png',
                            'student_intent_to_leave' => 'dark gray',
                            'student_intent_to_leave_image_name' => 'intent-to-leave-icons-dark-grey.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 1,
                            'last_activity_date' => '2015/11/03',
                            'last_activity' => 'Referral'
                        ],
                        [
                            'student_id' => 4776384,
                            'student_first_name' => 'Sutton',
                            'student_last_name' => 'Oconnor',
                            'external_id' => 4776384,
                            'student_primary_email' => 'MapworksBetaUser04776384@mailinator.com',
                            'student_status' => 1,
                            'student_risk_status' => 'green',
                            'student_risk_image_name' => 'risk-level-icon-g.png',
                            'student_intent_to_leave' => 'green',
                            'student_intent_to_leave_image_name' => 'leave-intent-stay-stated.png',
                            'student_classlevel' => '1st Year/Freshman',
                            'student_logins' => 1,
                            'last_activity_date' => '2015/11/03',
                            'last_activity' => 'Contact'
                        ]
                    ]
                ]
            ]
        ]);
    }
}