<?php
namespace Synapse\SurveyBundle\Repository;

use Synapse\SurveyBundle\Entity\Issue;
use Synapse\CoreBundle\Repository\SynapseRepository;

/**
 * IssueOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueOptionsRepository extends SynapseRepository
{
    const REPOSITORY_KEY = 'SynapseSurveyBundle:IssueOptions';
}