<?php
namespace Synapse\SurveyBundle\Repository;

use Synapse\SurveyBundle\Entity\Issue;
use Synapse\CoreBundle\Repository\SynapseRepository;

/**
 * IssueLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueLangRepository extends SynapseRepository
{
    const REPOSITORY_KEY = 'SynapseSurveyBundle:IssueLang';
}