<?php

namespace Synapse\SurveyeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyBlockRepository extends EntityRepository
{
}
