<?php

namespace Synapse\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * ESPRJ-13222; insert faculty headers
 */
class Version20180320170525 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='ExternalId'), `sort_order` = 1                ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AuthUsername'), `sort_order` = 2              ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Firstname'), `sort_order` = 3                    ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Lastname'), `sort_order` = 4                  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Title'), `sort_order` = 5                        ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address1'), `sort_order` = 6                  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address2'), `sort_order` = 7                     ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='City'), `sort_order` = 8                      ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Zip'), `sort_order` = 9                          ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='State'), `sort_order` = 10                    ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Country'), `sort_order` = 11                     ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobile'), `sort_order` = 12            ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobile'), `sort_order` = 13             ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='OfficePhone'), `sort_order` = 14              ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryEmail'), `sort_order` = 15                ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateEmail'), `sort_order` = 16           ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobileProvider'), `sort_order` = 17       ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobileProvider'), `sort_order` = 18  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='IsActive'), `sort_order` = 19                    ;");


        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='ExternalId'), `sort_order` = 1                ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AuthUsername'), `sort_order` = 2              ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Firstname'), `sort_order` = 3                    ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Lastname'), `sort_order` = 4                  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Title'), `sort_order` = 5                        ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address1'), `sort_order` = 6                  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address2'), `sort_order` = 7                     ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='City'), `sort_order` = 8                      ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Zip'), `sort_order` = 9                          ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='State'), `sort_order` = 10                    ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Country'), `sort_order` = 11                     ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobile'), `sort_order` = 12            ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobile'), `sort_order` = 13             ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='OfficePhone'), `sort_order` = 14              ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryEmail'), `sort_order` = 15                ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateEmail'), `sort_order` = 16           ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobileProvider'), `sort_order` = 17       ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobileProvider'), `sort_order` = 18  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='IsActive'), `sort_order` = 19                    ;");


        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='ExternalId'), `sort_order` = 1                ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AuthUsername'), `sort_order` = 2              ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Firstname'), `sort_order` = 3                    ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Lastname'), `sort_order` = 4                  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Title'), `sort_order` = 5                        ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address1'), `sort_order` = 6                  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address2'), `sort_order` = 7                     ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='City'), `sort_order` = 8                      ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Zip'), `sort_order` = 9                          ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='State'), `sort_order` = 10                    ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Country'), `sort_order` = 11                     ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobile'), `sort_order` = 12            ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobile'), `sort_order` = 13             ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='OfficePhone'), `sort_order` = 14              ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryEmail'), `sort_order` = 15                ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateEmail'), `sort_order` = 16           ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobileProvider'), `sort_order` = 17       ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobileProvider'), `sort_order` = 18  ;");
        $this->addSql("INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_dump'), `upload_id` = (select id from upload where upload_name = 'faculty'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='IsActive'), `sort_order` = 19                    ;");



    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
