<?php

namespace Synapse\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * ESPRJ-13222; adding headers for the student template and student data dump
 */
class Version20180319192836 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        /**
         * Inserting all of the template headers
         */
        $this->addSql(" INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='ExternalId'), `sort_order` = 1                                                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Firstname'), `sort_order` = 2                                                                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Lastname'), `sort_order` = 3                                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryEmail'), `sort_order` = 4                                                                ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='YearId'), `sort_order` = 5                                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='TermId'), `sort_order` = 6                                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Participating'), `sort_order` = 7                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='IsActive'), `sort_order` = 8                                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='RiskGroupId'), `sort_order` = 9                                                                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='RetentionTrack'), `sort_order` = 10                                                             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='SurveyCohort'), `sort_order` = 11                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='TransitionOneReceiveSurvey'), `sort_order` = 12                                                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='CheckupOneReceiveSurvey'), `sort_order` = 13                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='TransitionTwoReceiveSurvey'), `sort_order` = 14                                                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='CheckupTwoReceiveSurvey'), `sort_order` = 15                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryConnect'), `sort_order` = 16                                                             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='StudentPhoto'), `sort_order` = 17                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AuthUsername'), `sort_order` = 18                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address1'), `sort_order` = 19                                                                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address2'), `sort_order` = 20                                                                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='City'), `sort_order` = 21                                                                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Zip'), `sort_order` = 22                                                                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='State'), `sort_order` = 23                                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Country'), `sort_order` = 24                                                                    ;");
        
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusAddress'), `sort_order` = 25                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusCity'), `sort_order` = 26                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusState'), `sort_order` = 27                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusZip'), `sort_order` = 28                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusCountry'), `sort_order` = 29                        ;");
        
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobile'), `sort_order` = 30                                                              ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobileProvider'), `sort_order` = 31                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobile'), `sort_order` = 32                                                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobileProvider'), `sort_order` = 33                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='HomePhone'), `sort_order` = 34                                                                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateEmail'), `sort_order` = 35                                                             ;");
        
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'Gender'), `sort_order` = 36                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'BirthYear'), `sort_order` = 37                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MiddleName'), `sort_order` = 38                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'RaceEthnicity'), `sort_order` = 39                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StateInOut'), `sort_order` = 40                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'InternationalStudent'), `sort_order` = 41                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'GuardianEdLevel'), `sort_order` = 42                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'FirstGenStudent'), `sort_order` = 43                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MilitaryServedUS'), `sort_order` = 44                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MilitaryBenefitsUS'), `sort_order` = 45                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusResident'), `sort_order` = 46                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HonorsStudent'), `sort_order` = 47                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AthleteStudent'), `sort_order` = 48                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AthleteScholarship'), `sort_order` = 49                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AthleteSport'), `sort_order` = 50                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'FAFSASubmitted'), `sort_order` = 51                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'FedAidReceived'), `sort_order` = 52                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PellEligible'), `sort_order` = 53                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EFC'), `sort_order` = 54                                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'UnmetNeed'), `sort_order` = 55                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolNumber'), `sort_order` = 56                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolGPA'), `sort_order` = 57                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolPercentile'), `sort_order` = 58                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolGradYear'), `sort_order` = 59                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTComposite'), `sort_order` = 60                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTEnglish'), `sort_order` = 61                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTMath'), `sort_order` = 62                              ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTWriting'), `sort_order` = 63                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTScience'), `sort_order` = 64                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTReading'), `sort_order` = 65                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATMath'), `sort_order` = 66                              ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATComposite'), `sort_order` = 67                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATWriting'), `sort_order` = 68                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATCriticalRead'), `sort_order` = 69                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSPreAlgebra'), `sort_order` = 70                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSAlgebra'), `sort_order` = 71                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSCollegeAlgebra'), `sort_order` = 72                ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSGeometry'), `sort_order` = 73                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSTrig'), `sort_order` = 74                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSWriting'), `sort_order` = 75                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSReading'), `sort_order` = 76                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSESL'), `sort_order` = 77                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERSentence'), `sort_order` = 78                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERArithmetic'), `sort_order` = 79                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERAlgebra'), `sort_order` = 80                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERReading'), `sort_order` = 81                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ApplicationDate'), `sort_order` = 82                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AdmissionDate'), `sort_order` = 83                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AcceptDate'), `sort_order` = 84                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'OrientationDate'), `sort_order` = 85                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollYear'), `sort_order` = 86                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollTerm'), `sort_order` = 87                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollType'), `sort_order` = 88                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'DegreeSeeking'), `sort_order` = 89                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'IPEDSCohort'), `sort_order` = 90                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MajorCIP'), `sort_order` = 91                             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ProgramOnline'), `sort_order` = 92                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StartYearClassLevel'), `sort_order` = 93                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PreYearCredTotal'), `sort_order` = 94                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PreYearRemCredEarned'), `sort_order` = 95                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PreYearCumGPA'), `sort_order` = 96                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StartTermCredTotal'), `sort_order` = 97                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StartTermCredRem'), `sort_order` = 98                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollTimeStatus'), `sort_order` = 99                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MidCoursesFailing'), `sort_order` = 100                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermGPA'), `sort_order` = 101                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermCreditsEarned'), `sort_order` = 102                ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermCumGPA'), `sort_order` = 103                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermCumCreditsEarned'), `sort_order` = 104             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermRemCredPass'), `sort_order` = 105                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SAP'), `sort_order` = 106                                 ;");

        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name = 'EnrolledAtBeginningOfAcademicYear '), `sort_order` = 107  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name = 'EnrolledAtMidpointOfAcademicYear'), `sort_order` = 108    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name = 'CompletedADegree'), `sort_order` = 109                    ;");

        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'template'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'LevelofCompletion'), `sort_order` = 110                   ;");


        /**
         * inserting all of the data definition headers
         */
        $this->addSql(" INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='ExternalId'), `sort_order` = 1                                                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Firstname'), `sort_order` = 2                                                                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Lastname'), `sort_order` = 3                                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryEmail'), `sort_order` = 4                                                                ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='YearId'), `sort_order` = 5                                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='TermId'), `sort_order` = 6                                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Participating'), `sort_order` = 7                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='IsActive'), `sort_order` = 8                                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='RiskGroupId'), `sort_order` = 9                                                                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='RetentionTrack'), `sort_order` = 10                                                             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='SurveyCohort'), `sort_order` = 11                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='TransitionOneReceiveSurvey'), `sort_order` = 12                                                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='CheckupOneReceiveSurvey'), `sort_order` = 13                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='TransitionTwoReceiveSurvey'), `sort_order` = 14                                                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='CheckupTwoReceiveSurvey'), `sort_order` = 15                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryConnect'), `sort_order` = 16                                                             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='StudentPhoto'), `sort_order` = 17                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AuthUsername'), `sort_order` = 18                                                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address1'), `sort_order` = 19                                                                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Address2'), `sort_order` = 20                                                                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='City'), `sort_order` = 21                                                                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Zip'), `sort_order` = 22                                                                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='State'), `sort_order` = 23                                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='Country'), `sort_order` = 24                                                                    ;");

        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusAddress'), `sort_order` = 25                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusCity'), `sort_order` = 26                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusState'), `sort_order` = 27                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusZip'), `sort_order` = 28                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusCountry'), `sort_order` = 29                        ;");

        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobile'), `sort_order` = 30                                                              ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='PrimaryMobileProvider'), `sort_order` = 31                                                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobile'), `sort_order` = 32                                                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateMobileProvider'), `sort_order` = 33                                                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='HomePhone'), `sort_order` = 34                                                                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name ='AlternateEmail'), `sort_order` = 35                                                             ;");

        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'Gender'), `sort_order` = 36                               ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'BirthYear'), `sort_order` = 37                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MiddleName'), `sort_order` = 38                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'RaceEthnicity'), `sort_order` = 39                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StateInOut'), `sort_order` = 40                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'InternationalStudent'), `sort_order` = 41                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'GuardianEdLevel'), `sort_order` = 42                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'FirstGenStudent'), `sort_order` = 43                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MilitaryServedUS'), `sort_order` = 44                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MilitaryBenefitsUS'), `sort_order` = 45                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'CampusResident'), `sort_order` = 46                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HonorsStudent'), `sort_order` = 47                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AthleteStudent'), `sort_order` = 48                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AthleteScholarship'), `sort_order` = 49                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AthleteSport'), `sort_order` = 50                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'FAFSASubmitted'), `sort_order` = 51                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'FedAidReceived'), `sort_order` = 52                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PellEligible'), `sort_order` = 53                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EFC'), `sort_order` = 54                                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'UnmetNeed'), `sort_order` = 55                            ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolNumber'), `sort_order` = 56                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolGPA'), `sort_order` = 57                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolPercentile'), `sort_order` = 58                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'HighSchoolGradYear'), `sort_order` = 59                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTComposite'), `sort_order` = 60                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTEnglish'), `sort_order` = 61                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTMath'), `sort_order` = 62                              ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTWriting'), `sort_order` = 63                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTScience'), `sort_order` = 64                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACTReading'), `sort_order` = 65                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATMath'), `sort_order` = 66                              ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATComposite'), `sort_order` = 67                         ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATWriting'), `sort_order` = 68                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SATCriticalRead'), `sort_order` = 69                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSPreAlgebra'), `sort_order` = 70                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSAlgebra'), `sort_order` = 71                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSCollegeAlgebra'), `sort_order` = 72                ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSGeometry'), `sort_order` = 73                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSTrig'), `sort_order` = 74                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSWriting'), `sort_order` = 75                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSReading'), `sort_order` = 76                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'COMPASSESL'), `sort_order` = 77                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERSentence'), `sort_order` = 78                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERArithmetic'), `sort_order` = 79                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERAlgebra'), `sort_order` = 80                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ACCUPLACERReading'), `sort_order` = 81                    ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ApplicationDate'), `sort_order` = 82                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AdmissionDate'), `sort_order` = 83                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'AcceptDate'), `sort_order` = 84                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'OrientationDate'), `sort_order` = 85                      ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollYear'), `sort_order` = 86                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollTerm'), `sort_order` = 87                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollType'), `sort_order` = 88                           ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'DegreeSeeking'), `sort_order` = 89                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'IPEDSCohort'), `sort_order` = 90                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MajorCIP'), `sort_order` = 91                             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'ProgramOnline'), `sort_order` = 92                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StartYearClassLevel'), `sort_order` = 93                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PreYearCredTotal'), `sort_order` = 94                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PreYearRemCredEarned'), `sort_order` = 95                 ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'PreYearCumGPA'), `sort_order` = 96                        ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StartTermCredTotal'), `sort_order` = 97                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'StartTermCredRem'), `sort_order` = 98                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EnrollTimeStatus'), `sort_order` = 99                     ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'MidCoursesFailing'), `sort_order` = 100                   ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermGPA'), `sort_order` = 101                          ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermCreditsEarned'), `sort_order` = 102                ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermCumGPA'), `sort_order` = 103                       ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermCumCreditsEarned'), `sort_order` = 104             ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'EndTermRemCredPass'), `sort_order` = 105                  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'SAP'), `sort_order` = 106                                 ;");

        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name = 'EnrolledAtBeginningOfAcademicYear '), `sort_order` = 107  ;");
        $this->addSql("	INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name = 'EnrolledAtMidpointOfAcademicYear'), `sort_order` = 108    ;");
        $this->addSql(" INSERT INTO `synapse`.`upload_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `upload_column_header_id` = (select id from `upload_column_header` where upload_column_name = 'CompletedADegree'), `sort_order` = 109                    ;");


        $this->addSql("	INSERT INTO `synapse`.`upload_ebi_metadata_column_header_download_map` SET `ebi_download_type_id`=(select id from `ebi_download_type` where download_type = 'data_definition_file'), `upload_id` = (select id from upload where upload_name = 'student'), `ebi_metadata_id` = (select id from `ebi_metadata` where meta_key = 'LevelofCompletion'), `sort_order` = 110                   ;");

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
