<?php

namespace Synapse\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150612130920 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_AcademicUpdates_Header_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_CategoryType_Body_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_Course_Footer_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_Courses_Header_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_CoursesFaculty_Header_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_CoursesStudents_Header_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_CourseStudent_Footer_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_DateType_Body_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_Faculty_Header_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_NumberType_Body_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_StringType_Body_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_Student_Footer_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_Student_Header_Template','y');");
        $this->addSql("INSERT INTO `ebi_template` (`key`,`is_active`) VALUES ('Pdf_TextType_Body_Template','y');");
        
        
        $columnName = '$$column_name$$';
        $desctiption = '$$description$$';
        $length = '$$length$$';


        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_AcademicUpdates_Header_Template',@langid,NULL,'<!doctype html>\n<html>\n	<head>\n		<title></title>\n		<style>\n		    .container{\n				padding:60px 50px;\n			}\n			p,body{\n				margin:0;\n				color:#003366;\n			}\n			#outerContainer{\n				float:left;\n				width:100%;\n				box-sizing:border-box;\n			}\n			#outerContainer .align1{\n				float:left;\n				width:100%;\n			}\n			#outerContainer .columnNameContainer{\n				float:left;\n				display:inline-block;\n			}\n			#outerContainer .heading{\n				font-weight:bold;\n				font-size:22px;\n			}\n			#outerContainer .headingDiv{\n				margin-bottom:30px;\n			}\n			#outerContainer .subHeadingDiv{\n				margin-bottom:15px;\n				float: left;\n				width: 100%;\n			}\n			#outerContainer .userInfo{\n				margin-bottom:5px;\n			}\n			#outerContainer .userInfoDetails{\n				height:auto;\n				margin-bottom:15px;\n			}\n			#outerContainer .subHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .idHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .horizontalLine{\n				background-color: #ccc;\n				width:100%;\n				height:2px;\n			}\n			#outerContainer .horizontalDottedLine{\n			    border-bottom: dotted;\n				border-width: 4px; \n				color:#ccc;\n			}\n			#outerContainer .boldStyler{\n				font-weight:bold;\n			}\n			#outerContainer .columnNameContainer2{\n				width:30%;\n				height:auto;\n				padding:0px 10px;\n			}\n			#outerContainer .details{\n				width:30%;\n				height:auto;\n			}\n			#outerContainer .dataTypeContainer{\n				width:58%;\n				height:auto;\n			}\n			#outerContainer .userInfoHeading{\n				margin-bottom:3px;\n			}\n			#outerContainer .validvalues{\n				padding:0px 10px;\n			}\n			#outerContainer .italicStyler{\n				font-style:italic;\n			}\n		</style>\n	</head>\n	<body>\n	<div class=\"container\">\n		<div id=\"outerContainer\">\n			<div class=\"align1 headingDiv\">\n				<p class=\"heading\">MAP-Works: Academic Updates File Data Definitions<span><img src=\"\" /></span></p>\n			</div>\n			<div class=\"subHeadingDiv\">\n				<p class=\"subHeading\">General Academic Updates Information</p>\n				<div class=\"horizontalLine\"></div>\n			</div>\n		</div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_CategoryType_Body_Template',@langid,NULL,'<div id=\"outerContainer\">\n			<div class=\"align1 subHeadingDiv\">\n				<div class=\"columnNameContainer details\"><p class=\"idHeading\">$columnName</p></div>\n				<div class=\"columnNameContainer dataTypeContainer\"> <p>$desctiption</p></div>\n			</div>\n			<div class=\"align1 userInfo\">\n				<p class=\"userInfoHeading\">Upload Information</p>\n				<div class=\"horizontalDottedLine\"></div>\n			</div>\n			<div class=\"align1 userInfoDetails\">\n				<div class=\"columnNameContainer columnNameContainer2\"><p><span class=\"italicStyler\">Column Name:</span> <span class=\"boldStyler\">$columnName</span></p></div>\n				<div class=\"columnNameContainer dataTypeContainer\">\n					<p><span class=\"italicStyler\">Data Type:</span>Category</p>\n				</div>\n			</div></div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_Course_Footer_Template',@langid,NULL,'<p>Valid value that can be used to Inactive a Faculty member on a Course Section:-1</p>\n	</div>  \n   </body>\n</html>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_Courses_Header_Template',@langid,NULL,'<!doctype html>\n<html>\n	<head>\n		<title></title>\n		<style>\n			.container{\n				padding:60px 50px;\n			}\n			p,body{\n				margin:0;\n				color:#003366;\n			}\n			#outerContainer{\n				float:left;\n				width:100%;\n				box-sizing:border-box;\n			}\n			#outerContainer .align1{\n				float:left;\n				width:100%;\n			}\n			#outerContainer .columnNameContainer{\n				float:left;\n				display:inline-block;\n			}\n			#outerContainer .heading{\n				font-weight:bold;\n				font-size:22px;\n			}\n			#outerContainer .headingDiv{\n				margin-bottom:30px;\n			}\n			#outerContainer .subHeadingDiv{\n				margin-bottom:15px;\n				float: left;\n				width: 100%;\n			}\n			#outerContainer .userInfo{\n				margin-bottom:5px;\n			}\n			#outerContainer .userInfoDetails{\n				height:auto;\n				margin-bottom:15px;\n			}\n			#outerContainer .subHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .idHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .horizontalLine{\n				background-color: #ccc;\n				width:100%;\n				height:2px;\n			}\n			#outerContainer .horizontalDottedLine{\n			    border-bottom: dotted;\n				border-width: 4px; \n				color:#ccc;\n			}\n			#outerContainer .boldStyler{\n				font-weight:bold;\n			}\n			#outerContainer .columnNameContainer2{\n				width:30%;\n				height:auto;\n				padding:0px 10px;\n			}\n			#outerContainer .details{\n				width:30%;\n				height:auto;\n			}\n			#outerContainer .dataTypeContainer{\n				width:58%;\n				height:auto;\n			}\n			#outerContainer .userInfoHeading{\n				margin-bottom:3px;\n			}\n			#outerContainer .validvalues{\n				padding:0px 10px;\n			}\n			#outerContainer .italicStyler{\n				font-style:italic;\n			}\n		</style>\n	</head>\n	<body>\n	<div class=\"container\">\n		<div id=\"outerContainer\">\n			<div class=\"align1 headingDiv\">\n				<p class=\"heading\">MAP-Works: Courses and Sections File Data Definitions<span><img src=\"\" /></span></p>\n			</div>\n			<div class=\"subHeadingDiv\">\n				<p class=\"subHeading\">General Courses and Sections Information</p>\n				<div class=\"horizontalLine\"></div>\n			</div>\n		</div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_CoursesFaculty_Header_Template',@langid,NULL,'<!doctype html>\n<html>\n	<head>\n		<title></title>\n		<style>\n			.container{\n				padding:60px 50px;\n			}\n			p,body{\n				margin:0;\n				color:#003366;\n			}\n			#outerContainer{\n				float:left;\n				width:100%;\n				box-sizing:border-box;\n			}\n			#outerContainer .align1{\n				float:left;\n				width:100%;\n			}\n			#outerContainer .columnNameContainer{\n				float:left;\n				display:inline-block;\n			}\n			#outerContainer .heading{\n				font-weight:bold;\n				font-size:22px;\n			}\n			#outerContainer .headingDiv{\n				margin-bottom:30px;\n			}\n			#outerContainer .subHeadingDiv{\n				margin-bottom:15px;\n				float: left;\n				width: 100%;\n			}\n			#outerContainer .userInfo{\n				margin-bottom:5px;\n			}\n			#outerContainer .userInfoDetails{\n				height:auto;\n				margin-bottom:15px;\n			}\n			#outerContainer .subHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .idHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .horizontalLine{\n				background-color: #ccc;\n				width:100%;\n				height:2px;\n			}\n			#outerContainer .horizontalDottedLine{\n			    border-bottom: dotted;\n				border-width: 4px; \n				color:#ccc;\n			}\n			#outerContainer .boldStyler{\n				font-weight:bold;\n			}\n			#outerContainer .columnNameContainer2{\n				width:30%;\n				height:auto;\n				padding:0px 10px;\n			}\n			#outerContainer .details{\n				width:30%;\n				height:auto;\n			}\n			#outerContainer .dataTypeContainer{\n				width:58%;\n				height:auto;\n			}\n			#outerContainer .userInfoHeading{\n				margin-bottom:3px;\n			}\n			#outerContainer .validvalues{\n				padding:0px 10px;\n			}\n			#outerContainer .italicStyler{\n				font-style:italic;\n			}\n		</style>\n	</head>\n	<body>\n	<div class=\"container\">\n		<div id=\"outerContainer\">\n			<div class=\"align1 headingDiv\">\n				<p class=\"heading\">MAP-Works: Course Faculty/Staff File Data Definitions<span><img src=\"\" /></span></p>\n			</div>\n			<div class=\"subHeadingDiv\">\n				<p class=\"subHeading\">General Course Faculty/Staff Information</p>\n				<div class=\"horizontalLine\"></div>\n			</div>\n		</div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_CoursesStudents_Header_Template',@langid,NULL,'<!doctype html>\n<html>\n	<head>\n		<title></title>\n		<style>\n			.container{\n				padding:60px 50px;\n			}\n			p,body{\n				margin:0;\n				color:#003366;\n			}\n			#outerContainer{\n				float:left;\n				width:100%;\n				box-sizing:border-box;\n			}\n			#outerContainer .align1{\n				float:left;\n				width:100%;\n			}\n			#outerContainer .columnNameContainer{\n				float:left;\n				display:inline-block;\n			}\n			#outerContainer .heading{\n				font-weight:bold;\n				font-size:22px;\n			}\n			#outerContainer .headingDiv{\n				margin-bottom:30px;\n			}\n			#outerContainer .subHeadingDiv{\n				margin-bottom:15px;\n				float: left;\n				width: 100%;\n			}\n			#outerContainer .userInfo{\n				margin-bottom:5px;\n			}\n			#outerContainer .userInfoDetails{\n				height:auto;\n				margin-bottom:15px;\n			}\n			#outerContainer .subHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .idHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .horizontalLine{\n				background-color: #ccc;\n				width:100%;\n				height:2px;\n			}\n			#outerContainer .horizontalDottedLine{\n			    border-bottom: dotted;\n				border-width: 4px; \n				color:#ccc;\n			}\n			#outerContainer .boldStyler{\n				font-weight:bold;\n			}\n			#outerContainer .columnNameContainer2{\n				width:30%;\n				height:auto;\n				padding:0px 10px;\n			}\n			#outerContainer .details{\n				width:30%;\n				height:auto;\n			}\n			#outerContainer .dataTypeContainer{\n				width:58%;\n				height:auto;\n			}\n			#outerContainer .userInfoHeading{\n				margin-bottom:3px;\n			}\n			#outerContainer .validvalues{\n				padding:0px 10px;\n			}\n			#outerContainer .italicStyler{\n				font-style:italic;\n			}\n		</style>\n	</head>\n	<body>\n	<div class=\"container\">\n		<div id=\"outerContainer\">\n			<div class=\"align1 headingDiv\">\n				<p class=\"heading\">MAP-Works: Course Students File Data Definitions<span><img src=\"\" /></span></p>\n			</div>\n			<div class=\"subHeadingDiv\">\n				<p class=\"subHeading\">General Course Students Information</p>\n				<div class=\"horizontalLine\"></div>\n			</div>\n		</div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_CourseStudent_Footer_Template',@langid,NULL,'<p>Valid Value for Not Viewable(All other values will be considered as \"Viewable\"):0</p>\n	</div>  \n   </body>\n</html>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_DateType_Body_Template',@langid,NULL,'<div id=\"outerContainer\">\n			<div class=\"align1 subHeadingDiv\">\n				<div class=\"columnNameContainer details\"><p class=\"idHeading\">$columnName</p></div>\n				<div class=\"columnNameContainer dataTypeContainer\"> <p>$desctiption</p></div>\n			</div>\n			<div class=\"align1 userInfo\">\n				<p class=\"userInfoHeading\">Upload Information</p>\n				<div class=\"horizontalDottedLine\"></div>\n			</div>\n			<div class=\"align1 userInfoDetails\">\n				<div class=\"columnNameContainer columnNameContainer2\"><p><span class=\"italicStyler\">Column Name:</span> <span class=\"boldStyler\">$columnName</span></p></div>\n				<div class=\"columnNameContainer dataTypeContainer\">\n					<p><span class=\"italicStyler\">Data Type:</span>Date</p>\n				</div>\n			</div></div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_Faculty_Header_Template',@langid,NULL,'<!doctype html>\n<html>\n	<head>\n		<title></title>\n		<style>\n			.container{\n				padding:60px 50px;\n			}\n			p,body{\n				margin:0;\n				color:#003366;\n			}\n			#outerContainer{\n				float:left;\n				width:100%;\n				box-sizing:border-box;\n			}\n			#outerContainer .align1{\n				float:left;\n				width:100%;\n			}\n			#outerContainer .columnNameContainer{\n				float:left;\n				display:inline-block;\n			}\n			#outerContainer .heading{\n				font-weight:bold;\n				font-size:22px;\n			}\n			#outerContainer .headingDiv{\n				margin-bottom:30px;\n			}\n			#outerContainer .subHeadingDiv{\n				margin-bottom:15px;\n				float: left;\n				width: 100%;\n			}\n			#outerContainer .userInfo{\n				margin-bottom:5px;\n			}\n			#outerContainer .userInfoDetails{\n				height:auto;\n				margin-bottom:15px;\n			}\n			#outerContainer .subHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .idHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .horizontalLine{\n				background-color: #ccc;\n				width:100%;\n				height:2px;\n			}\n			#outerContainer .horizontalDottedLine{\n			    border-bottom: dotted;\n				border-width: 4px; \n				color:#ccc;\n			}\n			#outerContainer .boldStyler{\n				font-weight:bold;\n			}\n			#outerContainer .columnNameContainer2{\n				width:30%;\n				height:auto;\n				padding:0px 10px;\n			}\n			#outerContainer .details{\n				width:30%;\n				height:auto;\n			}\n			#outerContainer .dataTypeContainer{\n				width:58%;\n				height:auto;\n			}\n			#outerContainer .userInfoHeading{\n				margin-bottom:3px;\n			}\n			#outerContainer .validvalues{\n				padding:0px 10px;\n			}\n			#outerContainer .italicStyler{\n				font-style:italic;\n			}\n		</style>\n	</head>\n	<body>\n	<div class=\"container\">\n		<div id=\"outerContainer\">\n			<div class=\"align1 headingDiv\">\n				<p class=\"heading\">MAP-Works: Faculty/Staff File Data Definitions<span><img src=\"\" /></span></p>\n			</div>\n			<div class=\"subHeadingDiv\">\n				<p class=\"subHeading\">General Faculty/Staff Information</p>\n				<div class=\"horizontalLine\"></div>\n			</div>\n		</div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_NumberType_Body_Template',@langid,NULL,'<div id=\"outerContainer\">\n			<div class=\"align1 subHeadingDiv\">\n				<div class=\"columnNameContainer details\"><p class=\"idHeading\">$columnName</p></div>\n				<div class=\"columnNameContainer dataTypeContainer\"> <p>$desctiption</p></div>\n			</div>\n			<div class=\"align1 userInfo\">\n				<p class=\"userInfoHeading\">Upload Information</p>\n				<div class=\"horizontalDottedLine\"></div>\n			</div>\n			<div class=\"align1 userInfoDetails\">\n				<div class=\"columnNameContainer columnNameContainer2\"><p><span class=\"italicStyler\">Column Name:</span> <span class=\"boldStyler\">$columnName</span></p></div>\n				<div class=\"columnNameContainer dataTypeContainer\">\n					<p><span class=\"italicStyler\">Data Type:</span>Numbers Only</p>\n				</div>\n			</div></div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_StringType_Body_Template',@langid,NULL,'<div id=\"outerContainer\">\n			<div class=\"align1 subHeadingDiv\">\n				<div class=\"columnNameContainer details\"><p class=\"idHeading\">$columnName</p></div>\n				<div class=\"columnNameContainer dataTypeContainer\"> <p>$desctiption</p></div>\n			</div>\n			<div class=\"align1 userInfo\">\n				<p class=\"userInfoHeading\">Upload Information</p>\n				<div class=\"horizontalDottedLine\"></div>\n			</div>\n			<div class=\"align1 userInfoDetails\">\n				<div class=\"columnNameContainer columnNameContainer2\"><p><span class=\"italicStyler\">Column Name:</span> <span class=\"boldStyler\">$columnName</span></p></div>\n				<div class=\"columnNameContainer dataTypeContainer\">\n					<p><span class=\"italicStyler\">Data Type:</span>Letters and Numbers</p>\n					<p>(Max Length: $length characters)</p>\n				</div>\n			</div></div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_Student_Footer_Template',@langid,NULL,'<p>Note: For Pre-Defined Campus Groups,a code of \"-1\" can be uploaded to remove previously saved groups</p>\n	</div>  \n   </body>\n</html>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_Student_Header_Template',@langid,NULL,'<!doctype html>\n<html>\n	<head>\n		<title></title>\n		<style>\n			.container{\n				padding:60px 50px;\n			}\n			p,body{\n				margin:0;\n				color:#003366;\n			}\n			#outerContainer{\n				float:left;\n				width:100%;\n				box-sizing:border-box;\n			}\n			#outerContainer .align1{\n				float:left;\n				width:100%;\n			}\n			#outerContainer .columnNameContainer{\n				float:left;\n				display:inline-block;\n			}\n			#outerContainer .heading{\n				font-weight:bold;\n				font-size:22px;\n			}\n			#outerContainer .headingDiv{\n				margin-bottom:30px;\n			}\n			#outerContainer .subHeadingDiv{\n				margin-bottom:15px;\n				float: left;\n				width: 100%;\n			}\n			#outerContainer .userInfo{\n				margin-bottom:5px;\n			}\n			#outerContainer .userInfoDetails{\n				height:auto;\n				margin-bottom:15px;\n			}\n			#outerContainer .subHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .idHeading{\n				font-weight:bold;\n				font-size:18px;\n			}\n			#outerContainer .horizontalLine{\n				background-color: #ccc;\n				width:100%;\n				height:2px;\n			}\n			#outerContainer .horizontalDottedLine{\n			    border-bottom: dotted;\n				border-width: 4px; \n				color:#ccc;\n			}\n			#outerContainer .boldStyler{\n				font-weight:bold;\n			}\n			#outerContainer .columnNameContainer2{\n				width:30%;\n				height:auto;\n				padding:0px 10px;\n			}\n			#outerContainer .details{\n				width:30%;\n				height:auto;\n			}\n			#outerContainer .dataTypeContainer{\n				width:58%;\n				height:auto;\n			}\n			#outerContainer .userInfoHeading{\n				margin-bottom:3px;\n			}\n			#outerContainer .validvalues{\n				padding:0px 10px;\n			}\n			#outerContainer .italicStyler{\n				font-style:italic;\n			}\n		</style>\n	</head>\n	<body>\n	<div class=\"container\">\n		<div id=\"outerContainer\">\n			<div class=\"align1 headingDiv\">\n				<p class=\"heading\">MAP-Works: Student File Data Definitions<span><img src=\"\" /></span></p>\n			</div>\n			<div class=\"subHeadingDiv\">\n				<p class=\"subHeading\">General Student Information</p>\n				<div class=\"horizontalLine\"></div>\n			</div>\n		</div>');");
        $this->addSql("SET @langid := (SELECT id FROM language_master where langcode = 'en_US');
            INSERT INTO `ebi_template_lang` (`ebi_template_key`,`lang_id`,`description`,`body`) VALUES ('Pdf_TextType_Body_Template',@langid,NULL,'<div id=\"outerContainer\">\n			<div class=\"align1 subHeadingDiv\">\n				<div class=\"columnNameContainer details\"><p class=\"idHeading\">$columnName</p></div>\n				<div class=\"columnNameContainer dataTypeContainer\"> <p>$desctiption</p></div>\n			</div>\n			<div class=\"align1 userInfo\">\n				<p class=\"userInfoHeading\">Upload Information</p>\n				<div class=\"horizontalDottedLine\"></div>\n			</div>\n			<div class=\"align1 userInfoDetails\">\n				<div class=\"columnNameContainer columnNameContainer2\"><p><span class=\"italicStyler\">Column Name:</span> <span class=\"boldStyler\">$columnName</span></p></div>\n				<div class=\"columnNameContainer dataTypeContainer\">\n					<p><span class=\"italicStyler\">Data Type:</span>Text</p>\n					<p>(Max Length: $length characters)</p>\n				</div>\n			</div></div>');");
        
        
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        
    }
}
