/*
-- Query: SELECT * FROM synapse.activity_category_lang
LIMIT 0, 1000

-- Date: 2014-10-31 19:02
*/
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (1,1,1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic Issues');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (2,2,1,NULL,NULL,NULL,NULL,NULL,NULL,'Personal Issues');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (3,3,1,NULL,NULL,NULL,NULL,NULL,NULL,'Financial Issues');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (4,4,1,NULL,NULL,NULL,NULL,NULL,NULL,'MAPWorks');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (5,19,1,NULL,NULL,NULL,NULL,NULL,NULL,'Class attendance concern');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (6,20,1,NULL,NULL,NULL,NULL,NULL,NULL,'Class attendance positive');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (7,21,1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic performance concern');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (8,22,1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic performance positive');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (9,23,1,NULL,NULL,NULL,NULL,NULL,NULL,'Registration positive');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (10,24,1,NULL,NULL,NULL,NULL,NULL,NULL,'Registration concern');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (11,25,1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic skills');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (12,26,1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic major exploration/selection');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (13,27,1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic action meeting');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (14,28,1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic success planning');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (15,29,1,NULL,NULL,NULL,NULL,NULL,NULL,'Missing required meetings / activities');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (16,30,1,NULL,NULL,NULL,NULL,NULL,NULL,'Attended meeting / activities');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (17,31,1,NULL,NULL,NULL,NULL,NULL,NULL,'Other academic concerns');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (18,32,1,NULL,NULL,NULL,NULL,NULL,NULL,'Living environment concern');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (19,33,1,NULL,NULL,NULL,NULL,NULL,NULL,'Living environment positive');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (20,34,1,NULL,NULL,NULL,NULL,NULL,NULL,'Relationships concern');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (21,35,1,NULL,NULL,NULL,NULL,NULL,NULL,'Relationships positive');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (22,36,1,NULL,NULL,NULL,NULL,NULL,NULL,'Social connections concern');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (23,37,1,NULL,NULL,NULL,NULL,NULL,NULL,'Social connections positive');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (24,38,1,NULL,NULL,NULL,NULL,NULL,NULL,'Medical / mental health');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (25,39,1,NULL,NULL,NULL,NULL,NULL,NULL,'Short term');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (26,40,1,NULL,NULL,NULL,NULL,NULL,NULL,'Long term');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (27,41,1,NULL,NULL,NULL,NULL,NULL,NULL,'Positive financial');
INSERT INTO `activity_category_lang` (`id`,`activity_category_id`,`language_id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`description`) VALUES (28,42,1,NULL,NULL,NULL,NULL,NULL,NULL,'MAP-Works related issues');
