/*
-- Query: SELECT * FROM synapse.activity_category
LIMIT 0, 1000

-- Date: 2014-11-04 11:23
*/
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (1,NULL,NULL,NULL,NULL,NULL,NULL,'Academic Issues',NULL,NULL,NULL);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (2,NULL,NULL,NULL,NULL,NULL,NULL,'Personal Issues',NULL,NULL,NULL);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (3,NULL,NULL,NULL,NULL,NULL,NULL,'Financial Issues',NULL,NULL,NULL);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (4,NULL,NULL,NULL,NULL,NULL,NULL,'MAPWorks',NULL,NULL,NULL);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (19,NULL,NULL,NULL,NULL,NULL,NULL,'Class attendance concern',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (20,NULL,NULL,NULL,NULL,NULL,NULL,'Class attendance positive',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (21,NULL,NULL,NULL,NULL,NULL,NULL,'Academic performance concern',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (22,NULL,NULL,NULL,NULL,NULL,NULL,'Academic performance positive',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (23,NULL,NULL,NULL,NULL,NULL,NULL,'Registration positive',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (24,NULL,NULL,NULL,NULL,NULL,NULL,'Registration concern',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (25,NULL,NULL,NULL,NULL,NULL,NULL,'Academic skills',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (26,NULL,NULL,NULL,NULL,NULL,NULL,'Academic major exploration/selection',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (27,NULL,NULL,NULL,NULL,NULL,NULL,'Academic action meeting',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (28,NULL,NULL,NULL,NULL,NULL,NULL,'Academic success planning',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (29,NULL,NULL,NULL,NULL,NULL,NULL,'Missing required meetings / activities',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (30,NULL,NULL,NULL,NULL,NULL,NULL,'Attended meeting / activities',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (31,NULL,NULL,NULL,NULL,NULL,NULL,'Other academic concerns',NULL,NULL,1);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (32,NULL,NULL,NULL,NULL,NULL,NULL,'Living environment concern',NULL,NULL,2);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (33,NULL,NULL,NULL,NULL,NULL,NULL,'Living environment positive',NULL,NULL,2);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (34,NULL,NULL,NULL,NULL,NULL,NULL,'Relationships concern',NULL,NULL,2);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (35,NULL,NULL,NULL,NULL,NULL,NULL,'Relationships positive',NULL,NULL,2);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (36,NULL,NULL,NULL,NULL,NULL,NULL,'Social connections concern',NULL,NULL,2);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (37,NULL,NULL,NULL,NULL,NULL,NULL,'Social connections positive',NULL,NULL,2);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (38,NULL,NULL,NULL,NULL,NULL,NULL,'Medical / mental health',NULL,NULL,2);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (39,NULL,NULL,NULL,NULL,NULL,NULL,'Short term',NULL,NULL,3);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (40,NULL,NULL,NULL,NULL,NULL,NULL,'Long term',NULL,NULL,3);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (41,NULL,NULL,NULL,NULL,NULL,NULL,'Positive financial',NULL,NULL,3);
INSERT INTO `activity_category` (`id`,`created_by`,`created_at`,`modified_by`,`modified_at`,`deleted_by`,`deleted_at`,`short_name`,`is_active`,`display_seq`,`parent_activity_category_id`) VALUES (42,NULL,NULL,NULL,NULL,NULL,NULL,'MAP-Works related issues',NULL,NULL,4);
