INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (1, 1, 1, 'My High Priority Students Count for Dashboard');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (2, 2, 1, 'My Total Students Count for Dashboard group by Risk level');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (3, 3, 1, 'My High Priority Students List');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (4, 4, 1, 'My Total Students List for Dashboard');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (5, 5, 1, 'My Teams Open referrals Count, group by Teams, For the logged in User who is Team leader and date range');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (6, 6, 1, 'My Teams Interactions count, group by Teams, For the logged in User who is Team leader and date range');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (7, 7, 1, 'My Teams Logins count, group by Teams, For the logged in User who is Team leader  and date range');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (8, 8, 1, 'My Teams Open referrals Listing, For the passed team and date range');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (9, 9, 1, 'My Teams Interactions Listing, For the passed team and date range');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (10,10, 1, 'My Teams Logins Listing, For the passed team and date range');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (11, 11, 1, 'My Open Referrals received list');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (12, 12, 1, 'My Open referrals sent count');
INSERT INTO `synapse`.`ebi_search_lang` (`id`, `ebi_search_id`, `language_id`, `description`) VALUES (13, 13, 1, 'Top Issues count on Dashboard for passed Survey');
